### ISSUE TITLE
InlineMapping roadmap?

### ISSUE THREAD

**Issue by Thomas-Langlais** [JasonBock/InlineMapping#24]
I believe that Source Generators have a great use case for object mapping. As you've stated, the memory and execution time is vastly better if these object mappings are generated at compile-time instead of at runtime.
However, there are so many features that are available in AutoMapper that make the developer tooling better.

e.g. AutoMapper has a nested mapping feature described [here](https://github.com/AutoMapper/AutoMapper/blob/master/docs/Nested-mappings.md).

I believe this project has a lot of valid use-cases but lacks features in comparison to its competitors. I would like to develop this project with you if there is a project roadmap in some capacity.

**Comment by JasonBock** [comment]
You have a point that I don't have a roadmap anywhere. That's also somewhat deliberate :). My intent for this repository is not to "compete" with other projects; rather, it's a way to learn about source generators along with other development techniques. AutoMapper is feature-rich, and to put the time and energy into "repeating" that isn't all that appealing to me.

All that said, I'll consider have some kind of roadmap document here. If you have ideas to add to this project, feel free to add issues, and I could put them in the roadmap.

**Comment by Thomas-Langlais** [comment]
That's fair, I don't want to rob you of the original intentions of the project.
I also would like to use this as a learning experience, but also have an alternative to other object mappers.

**Comment by JasonBock** [comment]
I'd love to have some help/collaboration. Then I don't have to do everything :)

I'll get a roadmap done and committed. If you have features that you'd like to see added to InlineMapping, add them as issues and I'll review them.

**Comment by coderdnewbie** [comment]
Take a look at https://github.com/mrtaikandi/MapTo seems to be doing the same kind of source generator. Collaborate perhaps?

**Comment by JasonBock** [comment]
So, what I'm going to do is keep doing what I have been using: milestones. I really don't have a lot of plans for this package, other than "keep it simple". As long as features are suggested that make the developer's life easier and less complicated, I'll consider it.

I just created a 1.3.0 milestone (I'm going to release 1.2.0 today), and there are two issues that people could take if they want. I don't have any other issues/features in the pipeline, so....if people want to make suggestions, I'll triage them and figure out what milestone they go in.

@coderdnewbie I wasn't aware of MapTo, but....I'm going to keep this repo going. One other aspect is that I can use this as demo code for presentations I do, and I'd like to keep that sense of ownership.
